### ISSUE TITLE
Envoy no longer uses user's environment by default

### ISSUE THREAD

**Issue by mtnorthrop** [laravel/envoy#150]
- Envoy Version: 1.5.0
- Laravel Version: none; (I use Envoy for non-Laravel projects)

### Description:
Envoy 1.5.0 no longer loads the user's environment by default. Before 1.5.0, all of a user's environment variables were available by default when running Envoy tasks.

For example, in 1.4.1, this task:

```
@task('test', 'on' => ['localhost'])
echo $HOME
@endtask
```
would produce this output:
```
[127.0.0.1]: /home/myusername
```

However, after upgrading to 1.5.0, this no longer works and `$HOME` is no longer defined.

I'm just using `$HOME` as a simple example. In my case, my deployments broke because `envoy` stopped using my `$PATH` variable, and my `rsync` commands that use ssh keys also stopped working (it started asking me for my key's passphrase).

Based on some quick digging, it looks like the issue might have originated with commit [Add ENVOY environment var to allow checking host within tasks](https://github.com/laravel/envoy/commit/89b50dcbd3ec5e12b8aff4fbfe47abc451c725d5), on line 31 of `RemoteProcessor.php`.

I solved the issue for myself by rolling Envoy back to version 1.4.1.

**Comment by driesvints** [comment]
This doesn't work on 1.4.1 either for me. Afaik you always need to define your server.

**Comment by mtnorthrop** [comment]
My example was abridged, but there is a server (localhost) defined at the top. I'm sorry for not being more clear.

This is a complete example:
```
@servers([ 'localhost' => ['127.0.0.1']])

@task('test', 'on' => ['localhost'])
echo $HOME
@endtask
```

In this case, I would expect the output to be `[127.0.0.1]: /home/myusername`, the same as if I had created a bash file with the single command `echo $HOME`.

Instead, there is no output in 1.5.0 because the `$HOME` variable isn't set, but it _does_ work in 1.4.1.

My solution was to roll back to 1.4.1 and pin the version in my global `composer.json` file, so my immediate issue is resolved, but it's possible that others might experience this same behavior if they're using 1.5.0 or higher.

**Comment by driesvints** [comment]
@mtnorthrop your example still isn't valid. `@task('test', 'on' => ['localhost'])` isn't valid syntax. Did you try with `@task('test', ['on' => 'localhost'])`?

**Comment by mtnorthrop** [comment]
@driesvints I'm sorry, the `@task('test', 'on' => ['localhost'])` part in the original issue and the comment are both typos; this line is correctly written as `@task('test', ['on' => 'localhost'])` in my `Envoy.blade.php` file. I'll edit my issue and comment to fix this.

**Comment by driesvints** [comment]
Your example works for me on 1.5.0

**Comment by mtnorthrop** [comment]
Thanks for confirming.

I've just tested again, and the same script works for me on 1.4.1, but still doesn't work on 1.5.0. 

As a solution, I'll just keep envoy pinned to 1.4.1 in my global composer.json file.

It's possible that the issue is related to my local configuration or OS, which is Ubuntu 19.04. I hope, at least, that this thread might be useful if someone else runs into the same edgecase that I have.

**Comment by boyanraichev** [comment]
@mtnorthrop if you have multiple servers defined on several lines it would fail. No new lines should be present in the servers definition - otherwise I was getting the same error
